version: '2'

services:
  db:
    container_name: "postgres"
    image: postgres
  web:
    build: .
    container_name: "python-django"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db